"""Implementer agent for generating executable Python code for drug repositioning."""

from typing import Dict, Any, List, Optional
import time
import textwrap
from pathlib import Path
from loguru import logger


class ImplementerAgent:
    """Agent that generates executable Python code for computational experiments."""

    def __init__(self, config: Dict[str, Any]):
        self.config = config
        self.llm_plugin = config.get('llm_plugin')
        self.output_dir = config.get('output_dir', 'generated_code')
        self.max_retries = config.get('max_retries', 3)
        self.retry_delay = config.get('retry_delay', 1)

        Path(self.output_dir).mkdir(parents=True, exist_ok=True)
        logger.info(f"ImplementerAgent initialized, output dir: {self.output_dir}")

    def _retry_api_call(self, func, *args, **kwargs):
        """Retry API calls with exponential backoff."""
        import time
        attempt = 0
        last_error = None
        while attempt < self.max_retries:
            try:
                return func(*args, **kwargs)
            except Exception as e:
                last_error = e
                logger.warning(f"API call failed (attempt {attempt + 1}/{self.max_retries}): {e}")
                attempt += 1
                if attempt < self.max_retries:
                    wait_time = self.retry_delay * (2 ** attempt)
                    logger.info(f"Retrying in {wait_time}s...")
                    time.sleep(wait_time)
        raise last_error

    def _llm_generate(self, prompt: str, max_tokens: int = 2000) -> str:
        """Generate code with LLM with retries."""
        if not self.llm_plugin:
            logger.warning("LLM plugin not available, using templates")
            return ""

        try:
            return self._retry_api_call(self.llm_plugin.generate_text, prompt, max_tokens)
        except Exception as e:
            logger.error(f"LLM code generation failed: {e}")
            return ""

    def _generate_readme(self, design_doc: Dict[str, Any], script_name: str) -> str:
        """Generate README for generated implementation."""
        metadata = design_doc.get('metadata', {})
        drug = metadata.get('drug_candidate', 'Unknown')
        disease = metadata.get('target_disease', 'Unknown')

        readme = f"""# Implementation: {drug} for {disease}

Generated script: `{script_name}`

## Setup

```bash
pip install -r requirements_implementation.txt
```

## Usage

```bash
python {script_name}
```

## Configuration

Edit `config_implementation.json` to set:
- Input data paths
- Model hyperparameters
- Output directories
- Docking parameters (if applicable)

## Hardware Requirements

- CPU: 4+ cores recommended
- RAM: 16 GB minimum
- GPU: Optional (PyTorch/TensorFlow workflows)

## Checkpoints

Models and intermediate results are saved automatically to:
- `output/` directory
- CSV/JSON exports for analysis
- Trained models (joblib format)

## Troubleshooting

1. **Out of Memory**: Reduce batch size or use data generators
2. **Dependency conflicts**: Use conda env: `conda create -n pharma python=3.9`
3. **Runtime errors**: Check `implementation.log` for detailed tracebacks

## Next Steps

1. Prepare ChEMBL data or provide custom dataset
2. Adjust hyperparameters in config
3. Run baseline model (Random Forest)
4. Iterate with more complex models (GNN, Deep Learning)

Generated by ImplementerAgent
"""
        return readme

    def implement(self, design_doc: Dict[str, Any]) -> Dict[str, Any]:
        """Generate executable Python code from design document."""
        start_time = time.time()

        metadata = design_doc.get('metadata', {})
        drug = metadata.get('drug_candidate', 'Unknown')
        disease = metadata.get('target_disease', 'Unknown')

        model_type = design_doc.get('computational_model', {}).get('primary_model', 'QSAR')
        algorithms = design_doc.get('algorithms', {}).get('primary_algorithm', 'Random Forest')

        logger.info(f"Implementing design for {drug} -> {disease} ({model_type})")

        script_name = f"{drug.lower()}_{model_type}_{int(time.time())}.py"
        script_path = Path(self.output_dir) / script_name

        llm_code = self._llm_generate(f"Generate Python code for {drug} -> {disease} using {model_type}", max_tokens=4000)

        if llm_code and len(llm_code) > 500:
            final_code = llm_code
        else:
            final_code = f"""# Script: {script_name}
# Purpose: {model_type} for {drug} -> {disease}
# Generated by ImplementerAgent

import logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

def main():
    logger.info("Starting {model_type} experiment for {drug} -> {disease}")
    # TODO: Implement {model_type} pipeline
    print("Experiment script generated successfully")

if __name__ == "__main__":
    main()
"""

        with open(script_path, 'w', encoding='utf-8') as f:
            f.write(final_code)

        support_files = []
        readme = self._generate_readme(design_doc, script_name)
        readme_path = script_path.parent / f"README_{script_path.stem}.md"
        with open(readme_path, 'w', encoding='utf-8') as f:
            f.write(readme)
        support_files.append(str(readme_path))

        logger.success(f"Generated implementation: {script_path}")
        return {
            'drug': drug,
            'disease': disease,
            'model_type': model_type,
            'algorithm': algorithms,
            'main_script': str(script_path),
            'supporting_files': support_files,
            'execution_time_seconds': time.time() - start_time,
            'code_size_bytes': len(final_code),
            'llm_enhanced': bool(llm_code and len(llm_code) > 500),
            'metadata': metadata
        }

    def __repr__(self) -> str:
        return f"ImplementerAgent(output_dir={self.output_dir}, llm={'available' if self.llm_plugin else 'unavailable'})"