/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PapersRouteImport } from './routes/papers'
import { Route as MatrixRouteImport } from './routes/matrix'
import { Route as DiscoveriesRouteImport } from './routes/discoveries'
import { Route as IndexRouteImport } from './routes/index'

const PapersRoute = PapersRouteImport.update({
  id: '/papers',
  path: '/papers',
  getParentRoute: () => rootRouteImport,
} as any)
const MatrixRoute = MatrixRouteImport.update({
  id: '/matrix',
  path: '/matrix',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoveriesRoute = DiscoveriesRouteImport.update({
  id: '/discoveries',
  path: '/discoveries',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/discoveries': typeof DiscoveriesRoute
  '/matrix': typeof MatrixRoute
  '/papers': typeof PapersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discoveries': typeof DiscoveriesRoute
  '/matrix': typeof MatrixRoute
  '/papers': typeof PapersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/discoveries': typeof DiscoveriesRoute
  '/matrix': typeof MatrixRoute
  '/papers': typeof PapersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/discoveries' | '/matrix' | '/papers'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/discoveries' | '/matrix' | '/papers'
  id: '__root__' | '/' | '/discoveries' | '/matrix' | '/papers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiscoveriesRoute: typeof DiscoveriesRoute
  MatrixRoute: typeof MatrixRoute
  PapersRoute: typeof PapersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/papers': {
      id: '/papers'
      path: '/papers'
      fullPath: '/papers'
      preLoaderRoute: typeof PapersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matrix': {
      id: '/matrix'
      path: '/matrix'
      fullPath: '/matrix'
      preLoaderRoute: typeof MatrixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discoveries': {
      id: '/discoveries'
      path: '/discoveries'
      fullPath: '/discoveries'
      preLoaderRoute: typeof DiscoveriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiscoveriesRoute: DiscoveriesRoute,
  MatrixRoute: MatrixRoute,
  PapersRoute: PapersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
